clusterName: my-cluster
imagePullPolicy: Always
image: harbor.sc.garagen/jcrmindster/kafka-scada-json-producer
imageTag: 0.0.62

# Affinity for the pod assignment
# ref: https://kubernetes.io/docs/concepts/configuration/assign-pod-node/#affinity-and-anti-affinity
affinity: {}

# Configuration of the connection to the kafka broker
kafkaBroker:
  # The service name that exposes the kafka broker 
  serviceName: my-cluster-kafka-bootstrap
  # The namespace where the kafka broker is installed
  namespace: kafka
  # The port where the service listens for incomming connections
  servicePort: 9093
topics:
  consumer:
    name: scada
    partitions: 1
    replicas: 1
    group: scada-json-producer-2
  producer:
    name: scada-json
    partitions: 1
    replicas: 3
    interval_sec: 5
  lineOffset:
    name: scada-file-line-offset
    partitions: 1
    replicas: 3

