clusterName: my-cluster
imagePullPolicy: Always
image: jcrmindster/kafka-scada-json-producer
imageTag: 0.0.14
# Configuration of the connection to the kafka broker
kafkaBroker:
  # The service name that exposes the kafka broker 
  serviceName: my-cluster-kafka-bootstrap
  # The namespace where the kafka broker is installed
  namespace: kafka
  # The port where the service listens for incomming connections
  servicePort: 9093
topics:
  consumer:
    name: scada
    partitions: 1
    replicas: 1
  producer:
    name: scada-json
    partitions: 1
    replicas: 1
