clusterName: my-cluster
imagePullPolicy: Always
image: jcrmindster/kafka-scada-json-producer
imageTag: 0.0.13
kafkaBroker:
  serviceName: my-cluster-kafka-bootstrap
  serviceNamespace: kafka
  servicePort: 9093
topics:
  consumer:
    name: scada
    partitions: 1
    replicas: 1
  producer:
    name: scada-json
    partitions: 1
    replicas: 1
