apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: kafka-scada-json-producer
  name: kafka-scada-json-producer
spec:
  {{- with .Values.affinity }}
  affinity: 
  {{ toYaml . | indent 2}}
  {{- end }}
  selector:
    matchLabels:
      app: kafka-scada-json-producer
  template:
    metadata:
      labels:
        app: kafka-scada-json-producer
        application: grafana-kafka-scada
    spec:
      containers:
      - image: "{{ .Values.image }}:{{ .Values.imageTag }}"
        imagePullPolicy: {{ .Values.imagePullPolicy }}
        args: 
        - "{{ .Values.kafkaBroker.serviceName }}.{{ .Values.kafkaBroker.namespace }}:{{ .Values.kafkaBroker.servicePort }}"
        - {{ .Values.topics.consumer.name }}
        - {{ .Values.topics.producer.name }}
        - "{{ .Values.topics.producer.interval_sec }}"
        - {{  .Values.topics.lineOffset.name }}
        - {{ .Values.topics.consumer.group }}
        name: kafka-scada-json-producer
        resources:
          limits:
            cpu: 100m
            memory: 100Mi
